targets:
  debian-8:
    <<: *debian
  debian-9:
    <<: *debian
  ubuntu-12.04:
    <<: *debian
  ubuntu-14.04:
    <<: *debian
  ubuntu-16.04:
    <<: *debian
    build_dependencies:
      - bzr
      - mercurial
  centos-6: &el
    build_dependencies:
      - pam-devel
      # required for go buildpack
      - perl-Digest-SHA
    dependencies:
      - pam
      - git
  centos-7:
    <<: *el
before:
  - mv packager/Procfile .
after:
  - mv bin/gitea gitea
after_install: ./packager/hooks/postinst
buildpack: https://github.com/heroku/heroku-buildpack-go.git#v104
