targets:
  debian-9:
    build_dependencies:
      - libpam0g-dev
    dependencies:
      - libpam0g
      - git
      - nodejs
before:
  - mv packager/Procfile .
after:
  - mv bin/gitea gitea
after_install: ./packager/hooks/postinst
buildpack: https://github.com/heroku/heroku-buildpack-go.git#v148
